on:
  push:
    tags:
      - "*"
  workflow_dispatch:

jobs:
  test:
    name: Build And Test
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit
  publish-federated-identity-service:
    name: Publish Federated Identity Service
    uses: ./.github/workflows/publish-tom-federated-identity-service.yml
    needs: [test]
    secrets: inherit
  publish-tom-server:
    name: Publish ToM Server
    uses: ./.github/workflows/publish-tom-server.yml
    needs: [test]
    secrets: inherit
