name: Release

on:
  push:
    tags: ['*']
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    uses: ./.github/workflows/_test.yml
    with:
      skip-nx-cache: true

  publish-tom-server:
    name: Publish ToM Server
    needs: test
    uses: ./.github/workflows/_docker-publish.yml
    with:
      app-name: tom-server
      image-name: linagora/tom-server
      dockerfile: Dockerfile
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

  publish-federated-identity-service:
    name: Publish ToM Federated Identity Service
    needs: test
    uses: ./.github/workflows/_docker-publish.yml
    with:
      app-name: federated-identity-service
      image-name: linagora/tom-federated-identity-service
      dockerfile: packages/federated-identity-service/Dockerfile
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

  publish-tom-twp-cs-bridge:
    name: Publish Twake Common Settings Bridge
    needs: test
    uses: ./.github/workflows/_docker-publish.yml
    with:
      app-name: common-settings-bridge
      image-name: linagora/tom-twp-cs-bridge
      dockerfile: packages/common-settings-bridge/Dockerfile
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
