name: Release

on:
  push:
    tags: ['*']
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  test:
    name: Test
    uses: ./.github/workflows/_test.yml

  build:
    name: Build
    needs: [test]
    uses: ./.github/workflows/_build.yml
    with:
      upload-artifacts: true

  publish-tom-server:
    name: Publish tom-server
    needs: [build]
    uses: ./.github/workflows/_docker-publish.yml
    with:
      app-name: tom-server
      image-name: linagora/tom-server
      dockerfile: apps/tom-server/Dockerfile
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

  publish-federated-identity-service:
    name: Publish federated-identity-service
    needs: [build]
    uses: ./.github/workflows/_docker-publish.yml
    with:
      app-name: federated-identity-service
      image-name: linagora/tom-federated-identity-service
      dockerfile: apps/federated-identity-service/Dockerfile
    secrets:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
